### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arekpytka2812** [arekpytka2812/Taskify-Backend#11]
Entities:
- [ ]  Stats

Services:
- [ ]  crud services
- [ ]  email notification system
- [ ]  app notificatino system
- [ ]  backup service
- [ ]  data synchronization system (when offline changes)
